#!/bin/bash 

echo " Check the disk utilization in linux system "
disk_size=`df -h|grep /dev/xvda128|awk '{print $5}'|cut -d '%' -f1`
echo "$disk_size% of disk is filled "
if [ $disk_size -gt 80 ];
then 
   echo " disk is utilized more than 80% , expand sisk or delete some files "
else 
   echo " enough disk is available "
fi 
